name = "sh1107"
description = "Implementation of SH11107 OLED driver"
version = "1.2.0"

authors = ["Holger Rodriguez"]
maintainers = ["Holger Rodriguez <github@roseng.ch>"]
maintainers-logins = ["hgrodriguez"]
[[depends-on]]  # Added by alr
embedded_components = "~0.1.0"  # Added by alr
